# Generated by Django 4.0.6 on 2022-07-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0012_ledger_sundry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting_Voucher_Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_amount', models.CharField(max_length=255)),
                ('narration', models.CharField(max_length=500)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
            ],
        ),
    ]
