# Generated by Django 4.0.6 on 2022-07-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0013_accounting_voucher_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting_voucher_creation',
            name='voucher_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.voucher'),
        ),
        migrations.CreateModel(
            name='list_of_Vouchers_created',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.ledger')),
                ('voucher_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.accounting_voucher_creation')),
            ],
        ),
    ]
