# Generated by Django 4.0.6 on 2022-07-18 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0014_accounting_voucher_creation_voucher_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting_voucher_creation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies'),
        ),
        migrations.AlterField(
            model_name='accounting_voucher_creation',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.ledger'),
        ),
    ]
